// function to generate markdown for README
//line 5 was generated by going to shields.io, sizing and then github sizing. I then included the repo name of an actual repo that I have and placed it in a readme.md,  rt click on the file on the left and then open preview
//the ${data.name} section is actually where my name was "StevenSJones". ${data.name} dynamically creates ayones by taking their name and inserting it in that spot
function generateMarkdown(data) {
  return `
![GitHub repo size](https://img.shields.io/github/repo-size/${data.githubUser}/${data.githubRepo})

# Project Title: ${data.titleInput}
One Paragraph of project description goes here: ${data.descriptionInput}
    
## Table of Contents:
${data.tableOfContentsInput}

    
## Getting Started
These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.
    
## Prerequisites
What things you need to install the software and how to install them: 
${data.installationInput}
    
## Usage:
${data.usageInput}
    
## until finished
End with an example of getting some data out of the system or using it for a little demo
    
## Running the tests
Explain how to run the automated tests for this system
    
## Break down into end to end tests
Explain what these tests test and why
    
## Give an example
And coding style tests
Explain what these tests test and why:
${data.testsInput}
    
## Give an example
Deployment
Add additional notes about how to deploy this on a live system
    
## Built With:
${data.contributingInput}
Please read CONTRIBUTING.md for details on our code of conduct, and the process for submitting pull requests to us.
    
## Versioning
We use SemVer for versioning. For the versions available, see the tags on this repository.
    
## Authors
Billie Thompson - Initial work - PurpleBooth
See also the list of contributors who participated in this project.
Please provide any questions: 
${data.usageInput}
    
License
This project is licensed under: ${data.licenseInput} - see the LICENSE.md file for details
`;

}

module.exports = generateMarkdown;
