// function to generate markdown for README
//line 5 was generated by going to shields.io, sizing and then github sizing. I then included the repo name of an actual repo that I have and placed it in a readme.md,  rt click on the file on the left and then open preview
//the ${data.name} section is actually where my name was "StevenSJones". ${data.name} dynamically creates ayones by taking their name and inserting it in that spot
function generateMarkdown(data) {
  return `
![GitHub repo size](https://img.shields.io/github/repo-size/${data.githubUser}/${data.githubRepo})

# Project Title: ${data.titleInput}
One Paragraph of project description goes here: ${data.descriptionInput}
    
${data.tableOfContentsInput}
## Table of Contents:
- [title](#title)
- [Prerequisites](#Prerequisites)
- [Tests](#Tests)
- [Contributing](#Contributing)
- [Usage](#Usage) 
- [License](#License)

## Prerequisites:
What things you need to install the software and how to install them: 
> ${data.installationInput}
    
## Usage:
> ${data.usageInput}
    
## Tests:
> ${data.testsInput}
    
## Contributing:
> ${data.contributingInput}
    
## License
> [License Info](https://opensource.org/licenses/${data.licenseInput})
This project is licensed under: ${data.licenseInput} - see the LICENSE.md file for details
`;

}

module.exports = generateMarkdown;
